GET http://localhost:3001/api/blogs
###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Blog Title 003",
    "author": "Doe John",
    "url": "test.com",
    "likes": 2
}
###

DELETE http://localhost:3001/api/blogs/65489e9c047674b6f2eed2d2
###

PUT http://localhost:3001/api/blogs/6544ce86530a4df7bc859e75 HTTP/1.1
content-type: application/json

{
    "title": "Updated blog",
    "author": "Doe John",
    "url": "url.test.com",
    "likes": 777
}
###

GET http://localhost:3001/api/users
###

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "name": "John Doe 002",
    "username": "user002",
    "password": "johndoepassword002"
}